### ISSUE TITLE
sparkclr-submit debug only works once

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/Mobius#397]
If you call ``SparkCLR-submit.cmd debug``, and then connect using a client application, if that client application crashes, you can't reconnect to the debug hosted Spark. You have to stop it and then start it again, and then update your app.config file with the newly allocated port number. This is extremely frustrating.

**Comment by skaarthik** [comment]
The lifetime of sparkclr-submit is just for one Mobius app (i.e. launching JVM once). C# driver needs the port number from the JVM and hence app.config needs be updated every time the port number changes.

@isaacabraham - any suggestions on how the debug experience could be improved given these constraints?

**Comment by isaacabraham** [comment]
Given that restriction I would probably just run all this from the command line for testing and debug as rarely as possible :-/ I'm not sure how to get around this though - I'll have a think.

**Comment by isaacabraham** [comment]
Where will HDFS be pointing to by default?

**Comment by isaacabraham** [comment]
Is it possible to hard-code the port that spark uses?

**Comment by skaarthik** [comment]
It is possible but we do not want to reserve any port exclusively for Mobius. Dynamic port allocation is better.

**Comment by isaacabraham** [comment]
Of course. I was referring to be able to set it in a config file or supply as an argument.

**Comment by skaarthik** [comment]
Writing to the configuration file is a good idea. In other modes, an environment variable is used. Debug mode is not a common way to launch the app. That's why it has not received much attention on usability.

**Comment by isaacabraham** [comment]
How do people launch an application normally? Just command line?

**Comment by skaarthik** [comment]
Yes - using SparkCLR-submit.cmd

**Comment by anujk0292** [comment]
Spark Job Server is another option which does all the heavy lifting for you.

**Comment by isaacabraham** [comment]
From a development workflow, it's a far more productive easy to develop when you can simply run and debug from within the IDE. I'd strongly suggest giving this feature a better story.

**Comment by anujk0292** [comment]
IntelliJ supports job written in Scala as well its debugging. Don't know what level of support is offered by VS.

**Comment by isaacabraham** [comment]
Hmmm? VS has a debugger. It works with .NET. Just need to make the process ab it smoother for Mobius without needing to set configuration every time you run a job.

**Comment by skaarthik** [comment]
The steps to debug a Mobius app are straightforward. It would be nice to reduce the steps but considering the ROI I doubt that it will be prioritized in the project. PR is welcome to improve the debug experience.

**Comment by isaacabraham** [comment]
Debugging experience for complex data-driven workloads does not have a large ROI? Interesting.

**Comment by forki** [comment]
@isaacabraham Debugging is low-prio, tells you a lot ;-)

**Comment by anujk0292** [comment]
" considering the ROI", I have been developing mid size spark application
with scala, and believe me debugging has eased the development a lot.
Debugging should be given high priority.

**Comment by isaacabraham** [comment]
@skaarthik I can tell you this now - I would not consider using Spark / Mobius if the recommended development experience was "compile your app. go to console. launch spark. run application. check output files or console log to see if it worked". I suspect you'll find the same for many other developers as well.

**Comment by skaarthik** [comment]
This issue is not about whether to support debugging in Mobius or not. Debugging is obviously very important and it is currently supported. The improvement requested in this issue is to make the debugging experience better. As stated earlier, it would be nice if that could be done but here is some more context on the ROI.

When we talk about debugging a Mobius app, that usually means debugging the driver-side execution. Debugging what happens in the worker-side is much more interesting (IMO) and there is nothing special that is needed for that - the experience is same as that of attaching debugger to any process (CSharpWorker.exe). So, the value of debugging improvement in the context of this issue is limited to the driver-side only and for the value it adds within that scope, I believe, the current debug experience might be sufficient. That's why the ROI to eliminate one or two steps in the debug experience cannot be justified especially given the technical considerations listed below.

* Lifecycle of JVM/SparkContext (and hence sparkclr-submit): it does not make sense to alter the lifecycle just for the sake of debugging Mobius app allowing the reuse of JVM/SparkContext across different C# driver processes each with its own CLR/SparkContext. Making it transparent to the user only at the time of debug will lead to confusion as the non-debug workflow or semantics of launching/using SparkContext will be different.
* In order to improve the debugging experience, we have to solve the problem of state sharing (port number used by the socket) and management/synchronization (SparkContext lifetime) between JVM and CLR processes. I cannot think of a non-hacky approach that would enable a consistent experience and shared code path between debug and non-debug modes.

If there are specific recommendations to improving the debugging experience or pointers to other projects that have similar constraints but provide a better debug experience, I would be glad to revisit the topic of ROI.

**Comment by skaarthik** [comment]
Closing the issue due to inactivity. Please reopen if needed.

**Comment by isaacabraham** [comment]
Please don't close this - the debug mode is important. even if you don't want to fix this now, it's still an issue.
