### ISSUE TITLE
error launching worker in CentOS and OSX

### ISSUE THREAD

**Issue by skaarthik** [Microsoft/Mobius#468]
In CentOS and OSX, to execute Mobius either "binfmt_misc" has to be used or the [recommendation](http://www.mono-project.com/docs/getting-started/application-deployment/#layout-recommendation) of creating a script to call the application needs to be employed. Using the script for Mobius driver applications is straightforward but there is no way for doing that for CSharpWorker. 

Here is simple way to fix the problem:
* We will release CSharpWorker.sh.exe that will just point to CSharpWorker.exe with "mono" prefix (Mono path in this script needs to be configured by the user) 
* User will set the value of CSharpWorkerPath in the app.config of the driver application (similar to the debug mode) to "CSharpWorker.sh,exe" 

@qualiu & @kai-zeng - comments?

**Comment by qualiu** [comment]
@skaarthik - That's a good idea！I agree that leave trivial works  as little as possible to user.

**Comment by kai-zeng** [comment]
I have a slight different suggestion: instead of adding a CSharpWorker.sh.exe, what about we prefix the path with "mono" when we constructing csharpworker path in CSharpRDD.compute?

**Comment by skaarthik** [comment]
Adding "mono" will not be enough. I had to do the following in CSharpWorker.sh.exe to get it to work.
export PATH=$PATH:/opt/mono/bin
export PKG_CONFIG_PATH=/opt/mono/lib/pkgconfig

Adding these export statements to a script at /etc/profile.d and restarting Spark services did not help.

Maybe there is another way to set the right path and pkg config and in that case we could just prefix "mono" to worker path.

**Comment by qualiu** [comment]
First, I think it's better to solve it at the beginning:
1) Modifying the system once for all is not a best idea. (maybe that's why http://www.mono-project.com/docs/getting-started/application-deployment/#layout-recommendation)
2) Temporally changing as following is annoying and may impossible for user who can't get root permission :
echo ':CLR:M::MZ::/usr/bin/mono:' > /proc/sys/fs/binfmt_misc/register

So I think adding CSharpWorker.sh.exe is good idea.

Secondly, for the detail , I think it's better do it in an automatic way. Take mono path as example:
1) Try get it from user settings , like environment settings at first.
2) Automatically detect and get the mono-PATH (like "locate mono" or "whereis mono" ),
3) If failed to find mono, then asking user to provide the path.

**Comment by skaarthik** [comment]
@kai-zeng - any additional comments?

**Comment by kai-zeng** [comment]
I still think we don't need a launch script. Here are my reasons:

1. The official suggestions on deploying mono applications are very good. But it is worth noting that what they suggest is about user applications, not mono itself. They are not suggesting set the mono path every time. IMO it's pretty reasonable to assume mono and its libraries are in the system path, and users can directly run "mono xxx.exe" to launch application.
Therefore, I think it's not necessary to set mono path every time you launch something. The same thing applies to automatically detect mono path.

2. Except for the export statement, the csharpworker scirpt has only one line for launching. Then why not directly hard code this single line? We anyway don't (and we should not) change CSharpWorker very often.

**Comment by skaarthik** [comment]
@kai-zeng is looking into this issue

**Comment by skaarthik** [comment]
Added notes to use prefix script for worker using CSharpWorkerPath in app.config. See https://github.com/Microsoft/Mobius/commit/4f39658e4e68bb59c7960462ba5724895629101f.
