### ISSUE TITLE
Support for Cassandra

### ISSUE THREAD

**Issue by dwnichols** [Microsoft/Mobius#596]
It looks like Cassandra connectors for Spark are maintained through a third party packages. One specifically is by [Datastax](https://spark-packages.org/package/datastax/spark-cassandra-connector). 

Is support for third party integrations, specifically Cassandra connectors, on the roadmap for Mobius?

Also, would you consider a pull request where Cassandra support is optionally included as part of the build?

**Comment by dwnichols** [comment]
I didn't see that there was an example folder and I just searching the SparkCLR solution. 

The [CassandraDataFrame](https://github.com/Microsoft/Mobius/blob/master/examples/Sql/CassandraDataFrame/Program.cs) example answers a few questions.

**Comment by skaarthik** [comment]
Good that the existing example answered few questions.
Mobius does not interact with any connector directly. Mobius relies on Spark's functionality to load the data to Spark - this is true for Cassandra as well.

**Comment by dwnichols** [comment]
That makes sense, thanks Kaarthik.

I've run into another issue, along the same line. Each connector implementation can provide RDD implementations. These implementations may have extensions to the general scala RDD api to make data access more efficient for the underlying store. See [Cassandra data selection, filtering and grouping](https://github.com/datastax/spark-cassandra-connector/blob/master/doc/3_selection.md) and [Performing efficient joins](https://github.com/datastax/spark-cassandra-connector/blob/master/doc/2_loading.md#performing-efficient-joins-with-cassandra-tables-since-12). It's my understanding that Mobius would have to interact with these RDDs. How would I go about accessing one of these methods? Would I need to implement Cassandra specific extensions to Mobius' RDD classes?

**Comment by dwnichols** [comment]
@skaarthik any word on this?

**Comment by skaarthik** [comment]
@dwnichols - your assessment is correct. For RDD (and Unstructured Streaming), extensions are needed for data sources like Cassandra. Mobius has implemented extensions for Kafka and Eventhub for unstructured streaming. As far as RDDs, Mobius does not have any extension including the one that is needed for Cassandra. It is not too hard to implement such extensions for Mobius but at the same time it is not too easy because the underlying APIs needed in Mobius are not a part of its public API (should have been part of the public _dev_ API). HTH.

**Comment by skaarthik** [comment]
@dwnichols - closing this issue for now. Feel free to reopen if needed.
