### ISSUE TITLE
Possible ways to check the status of a job

### ISSUE THREAD

**Issue by hongjiedai** [Microsoft/Mobius#618]
Is there any way to get the current status of a submitted job?

I read the API and find that I can get the status as follows.

sparkContext.StatusTracker.GetJobInfo(0).Status

If I use the above code:
- Dose the ID of a job accumulate from '0'?
- Is the value returned from the above code the same with the string defined in 
https://spark.apache.org/docs/1.4.0/api/java/org/apache/spark/JobExecutionStatus.html

"
FAILED 
RUNNING 
SUCCEEDED 
UNKNOWN 
"

**Comment by dwnichols** [comment]
Hi @hongjiedai ,

Yes, you are correct. `sparkContext.StatusTracker.GetJobInfo(0).Status` is the job execution status from job id 0. Currently the method returns a string representation of the enum you linked. It would be nice if this was instead exposed as a strongly typed enum rather than a string.

**Comment by dwnichols** [comment]
I have created a pull request to expose an enum rather string: #622.

**Comment by dwnichols** [comment]
Hi @hongjiedai, I'm closing this issue as it looks like its the answer. #622 is merged to master.
