### ISSUE TITLE
SparkSession.SparkContext is internal

### ISSUE THREAD

**Issue by medvekoma** [Microsoft/Mobius#632]
I am trying to use the DataFrame API along with some broadcast variables, but I cannot reference SparkSession's SparkContext property because it is internal.

Is there any specific reason for marking this property "internal"? Is there any other way to use SparkSession and SparkContext in the same application?

**Comment by skaarthik** [comment]
@medvekoma - If you can do that in scala implementation but not in C#, it should be fixed in Mobius. I remember seeing an issue reported on this few months back but do not recall the details or the resolution. I will try to locate that issue. In the meantime, feel free to send PR if you are interested in fixing this.

**Comment by dwnichols** [comment]
@medvekoma is correct. The sparkContext is publicly available within the SparkSession class. Its defined in a constructor parameter [here](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/SparkSession.scala#L78).
